### ISSUE TITLE
Trouble understading statuscolors

### ISSUE THREAD

**Issue by pigeon46** [ashish-yadav11/dwmblocks#33]
Sorry, this might seem a bit noob-ish, but I'm having some trouble understanding exactly how the colored statusbar works, and I was hoping you could clear it for me. Firstly, do I have to patch in the statuscolor patch? Or does it already come with the patch you provided?

**Comment by ashish-yadav11** [comment]
No you don't have to do any more patches, its all in the one patch.

**Comment by ashish-yadav11** [comment]
You will have to expand the `*colors[][3]` array in your dwm `config.h`, then you can use the colors defined there in the status. You will have to output raw characters to switch color schemes in the status. Refer to statuscolors [site](https://dwm.suckless.org/patches/statuscolors/). There is just one difference that the raw characters start from `\x0b` rather than `\x01` as I have also mentioned in the README. Also refer to the blocks I have provided for example.
